//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProToExlForBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Name { get; set; }
        public string NomCher { get; set; }
        public string PosOtv { get; set; }
        public string Mass { get; set; }
        public string BurtNar { get; set; }
        public string Hei { get; set; }
        public string DiaNar { get; set; }
        public string ProxOtv { get; set; }
        public string TrubRez { get; set; }
        public string MetrRez { get; set; }
        public string VnutXvos { get; set; }
        public string NarXvos { get; set; }
        public string ProSRezSoe { get; set; }
        public string ScruRezFit { get; set; }
        public string NarOblKonCNakGai { get; set; }
        public string VnuPrisZakSize5 { get; set; }
        public string VnuPrisZakSize6 { get; set; }
        public string VnutKonCOblSet { get; set; }
        public string PramPodShar { get; set; }
        public string PramPodRuch { get; set; }
        public string RazPodKlu { get; set; }
        public string ProxOtvPodBurt { get; set; }
        public string NarDiaBurt { get; set; }
        public string PramPodStok { get; set; }
        public string VisVZakSost { get; set; }
        public string VisVOtkSost { get; set; }
        public string RazPodStok { get; set; }
        public string PosOtvSoStorXvos { get; set; }
        public string PosPodProclSize5 { get; set; }
        public string PosPodProclSize6 { get; set; }
        public string VnutKZaklSize5 { get; set; }
        public string VnutKZaklSize6 { get; set; }
    }
}
